// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TestBLOB.model
{
    [Table("FOTOS")]
    public partial class Foto
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [StringLength(40)]
        public string Beskrivelse { get; set; }
        [StringLength(10)]
        public string FileType { get; set; }
        [Column("Foto")]
        public byte[] Foto1 { get; set; }
    }
}